[package]
name = "file_server"
version = "2.5.2"
edition = "2021"
authors = ["Ploiu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# core technologies
rocket = { version = "0.5", features = ["json", "tls"] }
rusqlite = { version = "0.31", features = ["bundled"] }
# text encoding
base64 = "0.22"
sha2 = "0.10"


# logging
log = "0.4"
simple_logger = { version = "4.3", features = ["stderr", "colors", "timestamps"] }

# misc
regex = "1.10"
