[package]
name = "file_server"
version = "0.1.0"
edition = "2021"
authors = ["Ploiu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.3", features = ["json", "tls"] }
base64 = "0.21.5"
rusqlite = { version = "0.29.0", features = ["bundled"] }
sha2 = "0.10.8"
regex = "1.10.2"
