[package]
name = "file_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json", "tls"]}
base64 = "0.21.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
sha2 = "0.10.6"
regex = "1.7.1"
