[package]
name = "file_server"
version = "0.1.0"
edition = "2021"
authors = ["Ploiu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# core technologies
rocket = { version = "0.5.0-rc.3", features = ["json", "tls"] }
rusqlite = { version = "0.30.0", features = ["bundled"] }
# text encoding
base64 = "0.21.5"
sha2 = "0.10.8"

regex = "1.10.2"

# logging
log = "0.4.17"
simple_logger = { version = "4.3.0", features = ["stderr", "colors", "timestamps"] }
