[package]
name = "image_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"]}
serde = "1.0.143"
serde_json = "1.0.83"
base64 = "0.20.0-alpha.1"
rusqlite = { version = "0.28.0", features = ["bundled"] }
md5 = "0.7.0"