[default.tls]
# You will need to generate this yourself. Take a look at openssl for free ones
key = "./private-key.pem"
certs = "./cert.pem"

[default]
# make the temp directory on the same disk. This fixes issues with the server running on a different device from the temp directory
temp_dir = "./.file_server_temp"

[default.limits]
file = "100 Mib"
data-form = "100 Mib"
application-zip = "10Mib"

[global]
address = "0.0.0.0"
